[package]
name = "weight-wb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.1.0"
image = { version = "0.24.6", default-features = false, features = ["png"] }
imageproc = { version = "0.23.0", default-features = false }
rusb = "0.9.2"
rusttype = "0.9.3"
xi-unicode = "0.3.0"
